# Generated by Django 2.1.7 on 2019-03-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190313_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='cap',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='città',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='cognome',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='indirizzo',
        ),
    ]
